export interface JobSource {
  id: string;
  name: string;
  category: 'ATS' | 'AGGREGATOR' | 'REMOTE' | 'SEARCH' | 'PORTAL' | 'STARTUP';
  integrationMethod: 'API' | 'RSS' | 'SEARCH_PROVIDER' | 'IMPORT' | 'PARTNER';
  enabled: boolean;
  requiresCredential: boolean;
  hasCredential: boolean;
  refreshPolicy: 'hourly' | 'daily' | 'on_demand';
  attributionRequired: boolean;
  supportsLocation: boolean;
  supportsSalary: boolean;
  supportsCompany: boolean;
  supportsApplicationUrl: boolean;
  complianceNote?: string;
}

export const JOB_SOURCES_REGISTRY: JobSource[] = [
  // Google / Search Providers
  {
    id: 'serpapi_google_jobs',
    name: 'Google Jobs (SerpApi)',
    category: 'SEARCH',
    integrationMethod: 'SEARCH_PROVIDER',
    enabled: true,
    requiresCredential: true,
    hasCredential: !!process.env.SERPAPI_API_KEY,
    refreshPolicy: 'hourly',
    attributionRequired: true,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
    complianceNote: 'Permitted via SerpApi proxy search',
  },
  // Aggregators
  {
    id: 'adzuna',
    name: 'Adzuna API',
    category: 'AGGREGATOR',
    integrationMethod: 'API',
    enabled: true,
    requiresCredential: true,
    hasCredential: !!(process.env.ADZUNA_APP_ID && process.env.ADZUNA_APP_KEY),
    refreshPolicy: 'hourly',
    attributionRequired: true,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
  },
  {
    id: 'jooble',
    name: 'Jooble API',
    category: 'AGGREGATOR',
    integrationMethod: 'API',
    enabled: true,
    requiresCredential: true,
    hasCredential: !!process.env.JOOBLE_API_KEY,
    refreshPolicy: 'hourly',
    attributionRequired: true,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
  },
  {
    id: 'arbeitnow',
    name: 'Arbeitnow Jobs',
    category: 'AGGREGATOR',
    integrationMethod: 'API',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'hourly',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
  },
  // ATS Feeds
  {
    id: 'greenhouse',
    name: 'Greenhouse Boards',
    category: 'ATS',
    integrationMethod: 'API',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'hourly',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: false,
    supportsCompany: true,
    supportsApplicationUrl: true,
  },
  {
    id: 'lever',
    name: 'Lever Postings',
    category: 'ATS',
    integrationMethod: 'API',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'hourly',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: false,
    supportsCompany: true,
    supportsApplicationUrl: true,
  },
  {
    id: 'ashby',
    name: 'Ashby Public Postings',
    category: 'ATS',
    integrationMethod: 'API',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'hourly',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: false,
    supportsCompany: true,
    supportsApplicationUrl: true,
  },
  {
    id: 'workable',
    name: 'Workable Boards',
    category: 'ATS',
    integrationMethod: 'API',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'hourly',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: false,
    supportsCompany: true,
    supportsApplicationUrl: true,
  },
  {
    id: 'smartrecruiters',
    name: 'SmartRecruiters Public API',
    category: 'ATS',
    integrationMethod: 'API',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'hourly',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: false,
    supportsCompany: true,
    supportsApplicationUrl: true,
  },
  {
    id: 'recruitee',
    name: 'Recruitee Careers',
    category: 'ATS',
    integrationMethod: 'API',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'hourly',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: false,
    supportsCompany: true,
    supportsApplicationUrl: true,
  },
  {
    id: 'teamtailor',
    name: 'Teamtailor Feeds',
    category: 'ATS',
    integrationMethod: 'API',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'hourly',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: false,
    supportsCompany: true,
    supportsApplicationUrl: true,
  },
  // Remote Portals
  {
    id: 'jobicy',
    name: 'Jobicy Developer API',
    category: 'REMOTE',
    integrationMethod: 'API',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'hourly',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: false,
    supportsCompany: true,
    supportsApplicationUrl: true,
  },
  {
    id: 'himalayas',
    name: 'Himalayas Remote API',
    category: 'REMOTE',
    integrationMethod: 'API',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'hourly',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
  },
  {
    id: 'remotive',
    name: 'Remotive API',
    category: 'REMOTE',
    integrationMethod: 'API',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'hourly',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
  },
  {
    id: 'remoteok',
    name: 'RemoteOK JSON Feed',
    category: 'REMOTE',
    integrationMethod: 'RSS',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'daily',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
  },
  // Indian & Regional Portals (Manual / CSV / Search Provider Only)
  {
    id: 'naukri',
    name: 'Naukri.com',
    category: 'PORTAL',
    integrationMethod: 'IMPORT',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'on_demand',
    attributionRequired: true,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
    complianceNote: 'Direct automated scraping prohibited. Ingest via CSV or single-URL import.',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn Jobs',
    category: 'PORTAL',
    integrationMethod: 'SEARCH_PROVIDER',
    enabled: true,
    requiresCredential: true,
    hasCredential: !!process.env.SERPAPI_API_KEY,
    refreshPolicy: 'on_demand',
    attributionRequired: true,
    supportsLocation: true,
    supportsSalary: false,
    supportsCompany: true,
    supportsApplicationUrl: true,
    complianceNote: 'Automated direct scraping prohibited; permitted via SerpApi search provider.',
  },
  {
    id: 'indeed',
    name: 'Indeed',
    category: 'PORTAL',
    integrationMethod: 'SEARCH_PROVIDER',
    enabled: true,
    requiresCredential: true,
    hasCredential: !!process.env.SERPAPI_API_KEY,
    refreshPolicy: 'on_demand',
    attributionRequired: true,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
    complianceNote: 'Direct scraping prohibited; query via SerpApi or CSV import.',
  },
  {
    id: 'foundit',
    name: 'Foundit (Monster)',
    category: 'PORTAL',
    integrationMethod: 'IMPORT',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'on_demand',
    attributionRequired: true,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
    complianceNote: 'Import via user-supplied CSV or direct URL.',
  },
  {
    id: 'instahyre',
    name: 'Instahyre',
    category: 'PORTAL',
    integrationMethod: 'IMPORT',
    enabled: true,
    requiresCredential: true,
    hasCredential: false,
    refreshPolicy: 'on_demand',
    attributionRequired: true,
    supportsLocation: true,
    supportsSalary: false,
    supportsCompany: true,
    supportsApplicationUrl: true,
    complianceNote: 'Direct scraping prohibited; requires authenticated partner feed or CSV.',
  },
  {
    id: 'cutshort',
    name: 'Cutshort',
    category: 'PORTAL',
    integrationMethod: 'IMPORT',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'on_demand',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
    complianceNote: 'Import via CSV or direct job URL.',
  },
  {
    id: 'hirist',
    name: 'Hirist (Tech)',
    category: 'PORTAL',
    integrationMethod: 'IMPORT',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'on_demand',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
    complianceNote: 'Import via CSV or direct job URL.',
  },
  {
    id: 'iimjobs',
    name: 'iimjobs',
    category: 'PORTAL',
    integrationMethod: 'IMPORT',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'on_demand',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
    complianceNote: 'Import via CSV or direct job URL.',
  },
  {
    id: 'shine',
    name: 'Shine.com',
    category: 'PORTAL',
    integrationMethod: 'IMPORT',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'on_demand',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
    complianceNote: 'Import via CSV or direct job URL.',
  },
  {
    id: 'wellfound',
    name: 'Wellfound (AngelList)',
    category: 'STARTUP',
    integrationMethod: 'SEARCH_PROVIDER',
    enabled: true,
    requiresCredential: true,
    hasCredential: !!process.env.SERPAPI_API_KEY,
    refreshPolicy: 'on_demand',
    attributionRequired: true,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
    complianceNote: 'Access via search provider or authenticated API.',
  },
  {
    id: 'internshala',
    name: 'Internshala',
    category: 'PORTAL',
    integrationMethod: 'IMPORT',
    enabled: true,
    requiresCredential: false,
    hasCredential: true,
    refreshPolicy: 'on_demand',
    attributionRequired: false,
    supportsLocation: true,
    supportsSalary: true,
    supportsCompany: true,
    supportsApplicationUrl: true,
    complianceNote: 'Import via CSV or direct URL.',
  },
];
